<a href="https://colab.research.google.com/github/Rotha-Vichet/MLHW/blob/main/Assignment__KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task
1. Create a table between actual and predict
2. Check the formula of accuracy score 
3. Find teh procedure to get the optimnal K-value

# Create a table between actual and predict

In [2]:
import sklearn 
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing

In [3]:
from google.colab import files  # to import dataset manually
upload= files.upload()

Saving Iris.csv to Iris.csv


In [4]:
iris = pd.read_csv('Iris.csv')
iris.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
iris.shape

(150, 6)

In [6]:
iris.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [7]:
iris.values

array([[1, 5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [2, 4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [3, 4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4, 4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5, 5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [6, 5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [7, 4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [8, 5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [9, 4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [10, 4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [11, 5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [12, 4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [13, 4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [14, 4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [15, 5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [16, 5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [17, 5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [18, 5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [19, 5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [20, 5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [21, 5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
 

In [8]:
iris.isnull().head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0  False          False         False          False         False    False
1  False          False         False          False         False    False
2  False          False         False          False         False    False
3  False          False         False          False         False    False
4  False          False         False          False         False    False

In [9]:
x_variable = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']
y_variable = ['Species']
len(x_variable)
z = np.array(iris[x_variable]).reshape(-1,4)
w = np.array(iris[y_variable]).reshape(-1,1)
print(z.shape)
print(w.shape)

(150, 4)
(150, 1)


In [10]:
#  split the data set 
x_train, x_test, y_train, y_test = train_test_split(z, w, test_size = 0.2, random_state=1)
print(x_train.shape)
print(x_test.shape)

(120, 4)
(30, 4)


In [11]:
# model building with KNN algorithms
from sklearn.neighbors import KNeighborsClassifier
KNN_model = KNeighborsClassifier(n_neighbors = 5, n_jobs = -1).fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [12]:
y_predict = KNN_model.predict(x_test)
print(y_predict)

['Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-virginica']


In [13]:
KNN_model.predict_proba(x_test)

array([[1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0.8, 0.2],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0.6, 0.4],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0.4, 0.6]])

In [14]:
input = np.array([2, 4.5, 1, 6])
input = input.reshape(-1,4)

In [15]:
y_predict1 = KNN_model.predict(input)
print(y_predict1)

['Iris-setosa']


In [16]:
KNN_model.predict_proba(input)

array([[1., 0., 0.]])

In [17]:
# accuracy of the test dataset
from sklearn.metrics import accuracy_score
accuracy_res = accuracy_score(y_test, y_predict)
print(accuracy_res)

1.0


In [20]:
# Table comparison
y_test = y_test.reshape(-1)
print("y_predict        |  y_test")
print("-"*16, "|", "-"*17)
for i in range(len(y_predict)):
  if len(y_predict[i]) < 16:
    print(y_predict[i] , " "*(15-len(y_predict[i])) , "|", y_test[i])

y_predict        |  y_test
---------------- | -----------------
Iris-setosa      | Iris-setosa
Iris-versicolor  | Iris-versicolor
Iris-versicolor  | Iris-versicolor
Iris-setosa      | Iris-setosa
Iris-virginica   | Iris-virginica
Iris-versicolor  | Iris-versicolor
Iris-virginica   | Iris-virginica
Iris-setosa      | Iris-setosa
Iris-setosa      | Iris-setosa
Iris-virginica   | Iris-virginica
Iris-versicolor  | Iris-versicolor
Iris-setosa      | Iris-setosa
Iris-virginica   | Iris-virginica
Iris-versicolor  | Iris-versicolor
Iris-versicolor  | Iris-versicolor
Iris-setosa      | Iris-setosa
Iris-versicolor  | Iris-versicolor
Iris-versicolor  | Iris-versicolor
Iris-setosa      | Iris-setosa
Iris-setosa      | Iris-setosa
Iris-versicolor  | Iris-versicolor
Iris-versicolor  | Iris-versicolor
Iris-versicolor  | Iris-versicolor
Iris-setosa      | Iris-setosa
Iris-virginica   | Iris-virginica
Iris-versicolor  | Iris-versicolor
Iris-setosa      | Iris-setosa
Iris-setosa      | Iris-setosa
Iris-

In [19]:
# Table 2
y_test = y_test.reshape(-1)

import plotly.graph_objects as go

fig = go.Figure(data=[go.Table(header=dict(values=['Y_Predict', 'Y_Test']),
                 cells=dict(values=[y_predict, y_test]))
                     ])
fig.show()

# Check the formula of accuracy score

Formula : (TP + TN) / (TP + TN + FP + FN)

TP (True Positive): positive samples are predicted to positive correctly.

FN (False Positive): positive samples are predicted to negative wrongly.

FP (Fasle Negative): negative samples are predicted to postive wrongly.

TN (True Negative): negative samples are predicted to negative correctly.

(From : https://www.tutorialexample.com/an-introduction-to-accuracy-precision-recall-f1-score-in-machine-learning-machine-learning-tutorial/)


# Find the procedure to get the optimal k-value

Since K values can be choose randomly It is hard to pin point how to get K value that can have a stable discision boundaries. But we can do this:

- Find a plot in between error rate and K denoting values in a defined range. Then choose the K value as having a minimum error rate. 

- The lower the error of K values the higher the accuracy 
- We can also find the value of K from accuracy plot

(From : https://towardsdatascience.com/how-to-find-the-optimal-value-of-k-in-knn-35d936e554eb)